/**
 * TypeScript types for the YouTube Content Intelligence workflow.
 */

/** Result of a transcript fetch operation */
export interface TranscriptResult {
  /** Full transcript text */
  text: string;
  /** Language code (e.g., "pl", "en") */
  language: string;
  /** Whether the transcript was auto-generated by YouTube */
  isAutoGenerated: boolean;
}

/** Which tier successfully fetched the transcript */
export type TranscriptTier =
  | "innertube-web"
  | "innertube-android"
  | "html-parsing"
  | "supadata";

/** Extended result with metadata about the fetch */
export interface TranscriptFetchResult extends TranscriptResult {
  /** Which tier was used */
  tier: TranscriptTier;
  /** Video ID */
  videoId: string;
  /** Time taken in milliseconds */
  durationMs: number;
  /** Tiers that were attempted before success */
  tiersAttempted: TranscriptTier[];
}

/** Individual caption segment from YouTube */
export interface CaptionSegment {
  /** Start time in milliseconds */
  startMs: number;
  /** Duration in milliseconds */
  durationMs: number;
  /** Text content */
  text: string;
}

/** InnerTube API response structure (simplified) */
export interface InnerTubePlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: InnerTubeCaptionTrack[];
    };
  };
}

/** Caption track from InnerTube response */
export interface InnerTubeCaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string; // "asr" for auto-generated
  name?: { simpleText?: string };
}

/** Content scoring result */
export interface ContentScore {
  /** Brief summary of the content (2-3 sentences) */
  summary: string;
  /** Relevance score from 1 to 10 */
  score: number;
  /** Explanation of why this score was given */
  scoreReason: string;
  /** Content tags for categorization */
  tags: string[];
}

/** Full pipeline result combining transcript + score */
export interface ContentIntelResult {
  videoId: string;
  transcript: TranscriptFetchResult;
  scoring: ContentScore;
  processedAt: string;
}

/** AI provider configuration */
export type AIProvider = "openai" | "anthropic";

/** Scoring configuration */
export interface ScoringConfig {
  /** Which AI provider to use */
  provider: AIProvider;
  /** Model name (e.g., "gpt-4o", "claude-sonnet-4-20250514") */
  model: string;
  /** Maximum tokens for the response */
  maxTokens: number;
  /** System prompt for the scorer */
  systemPrompt: string;
}
