/**
 * YouTube Transcript Fetcher — 4-Tier Fallback
 *
 * Fetches YouTube video transcripts using a cascading fallback strategy:
 *
 * Tier 1: InnerTube Web API — uses YouTube's internal Web client API.
 *         Free, no API key needed. Works for most public videos.
 *
 * Tier 2: InnerTube Android API — same InnerTube API but with Android
 *         client headers. Bypasses some geo/age restrictions.
 *         Free, no API key needed.
 *
 * Tier 3: HTML Page Parsing — fetches the YouTube watch page and extracts
 *         captionTracks from embedded player data. Free, no API key needed.
 *         Works when InnerTube endpoints are blocked or rate-limited.
 *
 * Tier 4: Supadata API — paid third-party service as a last resort.
 *         Requires SUPADATA_API_KEY environment variable.
 *         Only attempted if env var is set.
 *
 * All tiers return: { text, language, isAutoGenerated }
 *
 * Usage:
 *   ANTHROPIC_API_KEY=your_key npx tsx youtube-transcript.ts
 *
 * @module youtube-transcript
 */

import type {
  TranscriptResult,
  TranscriptTier,
  TranscriptFetchResult,
  CaptionSegment,
  InnerTubePlayerResponse,
  InnerTubeCaptionTrack,
} from "./types";

// --- Constants ---

const INNERTUBE_API_URL =
  "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";

const WEB_CLIENT_CONTEXT = {
  client: {
    clientName: "WEB",
    clientVersion: "2.20240101.00.00",
    hl: "pl",
    gl: "PL",
  },
};

const ANDROID_CLIENT_CONTEXT = {
  client: {
    clientName: "ANDROID",
    clientVersion: "19.09.37",
    androidSdkVersion: 30,
    hl: "pl",
    gl: "PL",
  },
};

const ANDROID_USER_AGENT =
  "com.google.android.youtube/19.09.37 (Linux; U; Android 11) gzip";

const REQUEST_TIMEOUT_MS = 15_000;

// --- Helpers ---

/**
 * Extract video ID from a YouTube URL or return as-is if already an ID.
 */
export function extractVideoId(urlOrId: string): string {
  // Already a video ID (11 chars, alphanumeric + dash/underscore)
  if (/^[a-zA-Z0-9_-]{11}$/.test(urlOrId)) {
    return urlOrId;
  }

  const patterns = [
    /(?:youtube\.com\/watch\?v=)([a-zA-Z0-9_-]{11})/,
    /(?:youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,
  ];

  for (const pattern of patterns) {
    const match = urlOrId.match(pattern);
    if (match?.[1]) return match[1];
  }

  throw new Error(`Cannot extract video ID from: ${urlOrId}`);
}

/**
 * Fetch with timeout support.
 */
async function fetchWithTimeout(
  url: string,
  options: RequestInit = {},
  timeoutMs: number = REQUEST_TIMEOUT_MS
): Promise<Response> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetch(url, {
      ...options,
      signal: controller.signal,
    });
    return response;
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * Select the best caption track from a list.
 * Prefers: manual Polish > manual English > auto Polish > auto English > first available.
 */
function selectBestTrack(
  tracks: InnerTubeCaptionTrack[]
): InnerTubeCaptionTrack | null {
  if (tracks.length === 0) return null;

  // Priority: manual PL > manual EN > auto PL > auto EN > first
  const isAuto = (t: InnerTubeCaptionTrack) => t.kind === "asr";

  const manualPl = tracks.find(
    (t) => t.languageCode === "pl" && !isAuto(t)
  );
  if (manualPl) return manualPl;

  const manualEn = tracks.find(
    (t) => t.languageCode === "en" && !isAuto(t)
  );
  if (manualEn) return manualEn;

  const autoPl = tracks.find((t) => t.languageCode === "pl" && isAuto(t));
  if (autoPl) return autoPl;

  const autoEn = tracks.find((t) => t.languageCode === "en" && isAuto(t));
  if (autoEn) return autoEn;

  return tracks[0];
}

/**
 * Fetch caption text from a caption track URL and join segments.
 */
async function fetchCaptionText(
  baseUrl: string
): Promise<string> {
  // Request JSON3 format for structured captions
  const url = `${baseUrl}&fmt=json3`;
  const response = await fetchWithTimeout(url);

  if (!response.ok) {
    throw new Error(`Caption fetch failed: ${response.status}`);
  }

  const data = (await response.json()) as {
    events?: { segs?: { utf8?: string }[] }[];
  };

  if (!data.events) {
    throw new Error("No caption events in response");
  }

  const segments: string[] = [];
  for (const event of data.events) {
    if (event.segs) {
      for (const seg of event.segs) {
        if (seg.utf8 && seg.utf8.trim() !== "\n") {
          segments.push(seg.utf8.trim());
        }
      }
    }
  }

  return segments.join(" ").replace(/\s+/g, " ").trim();
}

// --- Tier 1: InnerTube Web API ---

/**
 * Tier 1: Fetch transcript via InnerTube Web API.
 *
 * Uses YouTube's internal API with WEB client context.
 * Free, no API key required. Works for most public videos.
 *
 * @param videoId - YouTube video ID (11 characters)
 * @returns TranscriptResult or throws on failure
 */
async function tier1InnertubeWeb(
  videoId: string
): Promise<TranscriptResult> {
  const body = JSON.stringify({
    videoId,
    context: WEB_CLIENT_CONTEXT,
  });

  const response = await fetchWithTimeout(INNERTUBE_API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body,
  });

  if (!response.ok) {
    throw new Error(`InnerTube Web API returned ${response.status}`);
  }

  const data = (await response.json()) as InnerTubePlayerResponse;
  const tracks =
    data.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!tracks || tracks.length === 0) {
    throw new Error("No caption tracks available (Tier 1)");
  }

  const bestTrack = selectBestTrack(tracks);
  if (!bestTrack) {
    throw new Error("Could not select caption track (Tier 1)");
  }

  const text = await fetchCaptionText(bestTrack.baseUrl);

  return {
    text,
    language: bestTrack.languageCode,
    isAutoGenerated: bestTrack.kind === "asr",
  };
}

// --- Tier 2: InnerTube Android API ---

/**
 * Tier 2: Fetch transcript via InnerTube Android API.
 *
 * Same InnerTube endpoint but with Android client headers.
 * Can bypass some restrictions that block the Web client.
 * Free, no API key required.
 *
 * @param videoId - YouTube video ID (11 characters)
 * @returns TranscriptResult or throws on failure
 */
async function tier2InnertubeAndroid(
  videoId: string
): Promise<TranscriptResult> {
  const body = JSON.stringify({
    videoId,
    context: ANDROID_CLIENT_CONTEXT,
  });

  const response = await fetchWithTimeout(INNERTUBE_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "User-Agent": ANDROID_USER_AGENT,
    },
    body,
  });

  if (!response.ok) {
    throw new Error(`InnerTube Android API returned ${response.status}`);
  }

  const data = (await response.json()) as InnerTubePlayerResponse;
  const tracks =
    data.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!tracks || tracks.length === 0) {
    throw new Error("No caption tracks available (Tier 2)");
  }

  const bestTrack = selectBestTrack(tracks);
  if (!bestTrack) {
    throw new Error("Could not select caption track (Tier 2)");
  }

  const text = await fetchCaptionText(bestTrack.baseUrl);

  return {
    text,
    language: bestTrack.languageCode,
    isAutoGenerated: bestTrack.kind === "asr",
  };
}

// --- Tier 3: HTML Page Parsing ---

/**
 * Tier 3: Fetch transcript by parsing the YouTube watch page HTML.
 *
 * Downloads the full watch page and extracts captionTracks from
 * the embedded ytInitialPlayerResponse JSON. Free, no API key required.
 * Useful when InnerTube endpoints are rate-limited or blocked.
 *
 * @param videoId - YouTube video ID (11 characters)
 * @returns TranscriptResult or throws on failure
 */
async function tier3HtmlParsing(
  videoId: string
): Promise<TranscriptResult> {
  const url = `https://www.youtube.com/watch?v=${videoId}`;
  const response = await fetchWithTimeout(url, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept-Language": "pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7",
    },
  });

  if (!response.ok) {
    throw new Error(`YouTube page returned ${response.status}`);
  }

  const html = await response.text();

  // Extract ytInitialPlayerResponse from the page
  const playerResponseMatch = html.match(
    /ytInitialPlayerResponse\s*=\s*({.+?})\s*;/
  );

  if (!playerResponseMatch?.[1]) {
    throw new Error("Could not find ytInitialPlayerResponse in page HTML");
  }

  let playerData: InnerTubePlayerResponse;
  try {
    playerData = JSON.parse(playerResponseMatch[1]);
  } catch {
    throw new Error("Failed to parse ytInitialPlayerResponse JSON");
  }

  const tracks =
    playerData.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!tracks || tracks.length === 0) {
    throw new Error("No caption tracks found in page HTML (Tier 3)");
  }

  const bestTrack = selectBestTrack(tracks);
  if (!bestTrack) {
    throw new Error("Could not select caption track (Tier 3)");
  }

  const text = await fetchCaptionText(bestTrack.baseUrl);

  return {
    text,
    language: bestTrack.languageCode,
    isAutoGenerated: bestTrack.kind === "asr",
  };
}

// --- Tier 4: Supadata API ---

/**
 * Tier 4: Fetch transcript via Supadata API (paid fallback).
 *
 * Uses the Supadata transcript API as a last resort.
 * Requires SUPADATA_API_KEY environment variable to be set.
 * If the env var is missing, this tier is skipped entirely.
 *
 * @see https://supadata.ai/docs
 * @param videoId - YouTube video ID (11 characters)
 * @returns TranscriptResult or throws on failure
 */
async function tier4Supadata(
  videoId: string
): Promise<TranscriptResult> {
  const apiKey = process.env.SUPADATA_API_KEY;
  if (!apiKey) {
    throw new Error(
      "SUPADATA_API_KEY not set — skipping Supadata tier"
    );
  }

  const url = `https://api.supadata.ai/v1/youtube/transcript?videoId=${videoId}&lang=pl`;
  const response = await fetchWithTimeout(url, {
    headers: {
      "x-api-key": apiKey,
    },
  });

  if (!response.ok) {
    throw new Error(`Supadata API returned ${response.status}`);
  }

  const data = (await response.json()) as {
    content?: { text?: string }[];
    lang?: string;
  };

  if (!data.content || data.content.length === 0) {
    throw new Error("Supadata returned empty transcript");
  }

  const text = data.content
    .map((segment) => segment.text ?? "")
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();

  return {
    text,
    language: data.lang ?? "pl",
    isAutoGenerated: false, // Supadata doesn't report this
  };
}

// --- Main Fetcher with Fallback ---

/** Tier definition for the fallback chain */
interface TierDefinition {
  name: TranscriptTier;
  fetcher: (videoId: string) => Promise<TranscriptResult>;
}

const TIERS: TierDefinition[] = [
  { name: "innertube-web", fetcher: tier1InnertubeWeb },
  { name: "innertube-android", fetcher: tier2InnertubeAndroid },
  { name: "html-parsing", fetcher: tier3HtmlParsing },
  { name: "supadata", fetcher: tier4Supadata },
];

/**
 * Fetch YouTube video transcript with 4-tier fallback.
 *
 * Tries each tier in order until one succeeds.
 * Returns the transcript along with metadata about which tier was used.
 *
 * @param urlOrId - YouTube URL or video ID
 * @returns TranscriptFetchResult with text, language, tier info, and timing
 * @throws Error if all tiers fail
 *
 * @example
 * ```typescript
 * const result = await fetchTranscript("dQw4w9WgXcQ");
 * console.log(result.text);       // Full transcript text
 * console.log(result.tier);       // "innertube-web"
 * console.log(result.language);   // "en"
 * ```
 */
export async function fetchTranscript(
  urlOrId: string
): Promise<TranscriptFetchResult> {
  const videoId = extractVideoId(urlOrId);
  const start = Date.now();
  const tiersAttempted: TranscriptTier[] = [];
  const errors: string[] = [];

  for (const tier of TIERS) {
    tiersAttempted.push(tier.name);

    try {
      console.log(`[Transcript] Trying ${tier.name}...`);
      const result = await tier.fetcher(videoId);

      if (!result.text || result.text.length < 10) {
        throw new Error("Transcript too short (likely empty)");
      }

      console.log(
        `[Transcript] Success via ${tier.name} (${result.text.length} chars, ${result.language})`
      );

      return {
        ...result,
        tier: tier.name,
        videoId,
        durationMs: Date.now() - start,
        tiersAttempted,
      };
    } catch (error) {
      const message =
        error instanceof Error ? error.message : String(error);
      errors.push(`${tier.name}: ${message}`);
      console.log(`[Transcript] ${tier.name} failed: ${message}`);
    }
  }

  throw new Error(
    `All transcript tiers failed for video ${videoId}:\n${errors.join("\n")}`
  );
}

// --- CLI Entry Point ---

async function main(): Promise<void> {
  const videoUrl = process.argv[2];
  if (!videoUrl) {
    console.log("Usage: npx tsx youtube-transcript.ts <youtube-url-or-id>");
    console.log("Example: npx tsx youtube-transcript.ts dQw4w9WgXcQ");
    process.exit(1);
  }

  try {
    const result = await fetchTranscript(videoUrl);
    console.log("\n=== Transcript Result ===");
    console.log(`Video ID: ${result.videoId}`);
    console.log(`Tier used: ${result.tier}`);
    console.log(`Language: ${result.language}`);
    console.log(`Auto-generated: ${result.isAutoGenerated}`);
    console.log(`Length: ${result.text.length} chars`);
    console.log(`Time: ${result.durationMs}ms`);
    console.log(`Tiers attempted: ${result.tiersAttempted.join(" → ")}`);
    console.log(`\n--- First 500 chars ---\n${result.text.slice(0, 500)}...`);
  } catch (error) {
    console.error("Failed to fetch transcript:", error);
    process.exit(1);
  }
}

main();
